version: "3.8"
services:
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: spotify_sync
        ports:
            - "5432:5432"

    backend:
        build: .
        environment:
            DATABASE_URL: postgresql://user:password@db:5432/spotify_sync
        ports:
            - "5000:5000"
        depends_on:
            - db

    frontend:
        image: node:18
        working_dir: /app
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "5173:5173"
        command: ["sh", "-c", "npm install && npm run dev"]
        environment:
            - VITE_PORT=5173
            - CHOKIDAR_USEPOLLING=true # Ensures hot reload works in Docker
